/*
 * blog_aws_reference_data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-10-30T10:36:19Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package blog.aws.referencedata.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import blog.aws.referencedata.sdk.model.DealerDealerLocations;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A Dealer in the Reference Data
 */
@ApiModel(description = "A Dealer in the Reference Data")
@JsonPropertyOrder({
  Dealer.JSON_PROPERTY_CODE,
  Dealer.JSON_PROPERTY_NAME,
  Dealer.JSON_PROPERTY_LOCKED,
  Dealer.JSON_PROPERTY_U_U_I_D,
  Dealer.JSON_PROPERTY_EFFECTIVE_DATE,
  Dealer.JSON_PROPERTY_EXPIRATION_DATE,
  Dealer.JSON_PROPERTY_DEALER_LOCATIONS
})

public class Dealer {
  public static final String JSON_PROPERTY_CODE = "Code";
  private String code;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_LOCKED = "Locked";
  private Boolean locked;

  public static final String JSON_PROPERTY_U_U_I_D = "UUID";
  private String UUID;

  public static final String JSON_PROPERTY_EFFECTIVE_DATE = "EffectiveDate";
  private String effectiveDate;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "ExpirationDate";
  private String expirationDate;

  public static final String JSON_PROPERTY_DEALER_LOCATIONS = "DealerLocations";
  private List<DealerDealerLocations> dealerLocations = null;


  public Dealer code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Code representing the Gender
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code representing the Gender")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Dealer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the Gender
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the Gender")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Dealer locked(Boolean locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * If the Item is locked for updates
   * @return locked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the Item is locked for updates")
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLocked() {
    return locked;
  }


  public void setLocked(Boolean locked) {
    this.locked = locked;
  }


  public Dealer UUID(String UUID) {
    
    this.UUID = UUID;
    return this;
  }

   /**
   * Identifier
   * @return UUID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier")
  @JsonProperty(JSON_PROPERTY_U_U_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUUID() {
    return UUID;
  }


  public void setUUID(String UUID) {
    this.UUID = UUID;
  }


  public Dealer effectiveDate(String effectiveDate) {
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Date the item comes into effect
   * @return effectiveDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date the item comes into effect")
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }


  public Dealer expirationDate(String expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Date the item stops being in effect
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date the item stops being in effect")
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }


  public Dealer dealerLocations(List<DealerDealerLocations> dealerLocations) {
    
    this.dealerLocations = dealerLocations;
    return this;
  }

  public Dealer addDealerLocationsItem(DealerDealerLocations dealerLocationsItem) {
    if (this.dealerLocations == null) {
      this.dealerLocations = new ArrayList<>();
    }
    this.dealerLocations.add(dealerLocationsItem);
    return this;
  }

   /**
   * Locations of the Dealer
   * @return dealerLocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Locations of the Dealer")
  @JsonProperty(JSON_PROPERTY_DEALER_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DealerDealerLocations> getDealerLocations() {
    return dealerLocations;
  }


  public void setDealerLocations(List<DealerDealerLocations> dealerLocations) {
    this.dealerLocations = dealerLocations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dealer dealer = (Dealer) o;
    return Objects.equals(this.code, dealer.code) &&
        Objects.equals(this.name, dealer.name) &&
        Objects.equals(this.locked, dealer.locked) &&
        Objects.equals(this.UUID, dealer.UUID) &&
        Objects.equals(this.effectiveDate, dealer.effectiveDate) &&
        Objects.equals(this.expirationDate, dealer.expirationDate) &&
        Objects.equals(this.dealerLocations, dealer.dealerLocations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, locked, UUID, effectiveDate, expirationDate, dealerLocations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dealer {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    UUID: ").append(toIndentedString(UUID)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    dealerLocations: ").append(toIndentedString(dealerLocations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

