/*
 * blog_aws_reference_data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-10-29T19:55:50Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package blog.aws.referencedata.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A Gender in the Reference Data
 */
@ApiModel(description = "A Gender in the Reference Data")
@JsonPropertyOrder({
  Gender.JSON_PROPERTY_CODE,
  Gender.JSON_PROPERTY_NAME,
  Gender.JSON_PROPERTY_LOCKED,
  Gender.JSON_PROPERTY_U_U_I_D,
  Gender.JSON_PROPERTY_EFFECTIVE_DATE,
  Gender.JSON_PROPERTY_EXPIRATION_DATE
})

public class Gender {
  public static final String JSON_PROPERTY_CODE = "Code";
  private String code;

  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_LOCKED = "Locked";
  private Boolean locked;

  public static final String JSON_PROPERTY_U_U_I_D = "UUID";
  private String UUID;

  public static final String JSON_PROPERTY_EFFECTIVE_DATE = "EffectiveDate";
  private String effectiveDate;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "ExpirationDate";
  private String expirationDate;


  public Gender code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Code representing the Gender
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code representing the Gender")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Gender name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the Gender
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the Gender")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Gender locked(Boolean locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * If the Item is locked for updates
   * @return locked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the Item is locked for updates")
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLocked() {
    return locked;
  }


  public void setLocked(Boolean locked) {
    this.locked = locked;
  }


  public Gender UUID(String UUID) {
    
    this.UUID = UUID;
    return this;
  }

   /**
   * Identifier
   * @return UUID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier")
  @JsonProperty(JSON_PROPERTY_U_U_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUUID() {
    return UUID;
  }


  public void setUUID(String UUID) {
    this.UUID = UUID;
  }


  public Gender effectiveDate(String effectiveDate) {
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Date the item comes into effect
   * @return effectiveDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date the item comes into effect")
  @JsonProperty(JSON_PROPERTY_EFFECTIVE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }


  public Gender expirationDate(String expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Date the item stops being in effect
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date the item stops being in effect")
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Gender gender = (Gender) o;
    return Objects.equals(this.code, gender.code) &&
        Objects.equals(this.name, gender.name) &&
        Objects.equals(this.locked, gender.locked) &&
        Objects.equals(this.UUID, gender.UUID) &&
        Objects.equals(this.effectiveDate, gender.effectiveDate) &&
        Objects.equals(this.expirationDate, gender.expirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, locked, UUID, effectiveDate, expirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Gender {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    UUID: ").append(toIndentedString(UUID)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

